name: snowflake_devops

# controls when the action will run
on: 
   push:
     branches :
       - main
         paths
          -'finalscripts/**'

 # Allow you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
jobs:
  deploy_snowflake_changes-job:
   runs-on : ubuntu-22.04 latest
  
   steps: 
    # checks-out repository under $GITHUB_WORKSPACE
   - name: Checkout repository
     uses: actions/checkout@v2

   - name: use Python 3.8.x
     uses: actions/setup-Python@v2.2.1
     with:
        python-vesion: 3.8.x

   - name: Run schemachange
     env:
         SF_ACCOUNT: ${(secrets.SF_ACCOUNT)}
         SF_USERNAME: ${(secrets.SF_USERNAME)}
         SF_ROLE: ${(secrets.SF_ROLE)}
         SF_WAREHOUSE: ${(secrets.SF_WAREHOUSE)}
         SF_DATABASE: ${(secrets.SF_DATABASE)}
         SNOWFLAKE_PASSWORD: ${(secrets.SF_PASSWORD)}
     run: |
       echo "GITHUB_WORKSPACE: $GITHUBREPO"
       python --version
       echo  "Step 1 : Installing schemachange"
       pip install schemachange

       echo "Step 2 : running schemachange "
       schemachange -f $GITHUB_WORKSPACE/finalscripts -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE  -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history                               

